function binfieldbikey = importfile_bin_bike_y(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   BINFIELDBIKEY = IMPORTFILE(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   BINFIELDBIKEY = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   binfieldbikey = importfile('binfield_bike_y.txt', 2, 504);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2024/01/03 11:51:21

%% Initialize variables.
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*3s%24s%14s%14s%13s%13s%13s%13s%14s%14s%13s%14s%13s%13s%14s%14s%13s%13s%13s%13s%14s%14s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%14s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%13s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'WhiteSpace', '', 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240]
    % Converts text in the input cell array to numbers. Replaced non-numeric text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;

            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^[-/+]*\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
binfieldbikey = table;
binfieldbikey.FieldBike15cmBlockMe = cell2mat(raw(:, 1));
binfieldbikey.shLast500I = cell2mat(raw(:, 2));
binfieldbikey.terations300 = cell2mat(raw(:, 3));
binfieldbikey.VarName5 = cell2mat(raw(:, 4));
binfieldbikey.VarName6 = cell2mat(raw(:, 5));
binfieldbikey.VarName7 = cell2mat(raw(:, 6));
binfieldbikey.VarName8 = cell2mat(raw(:, 7));
binfieldbikey.VarName9 = cell2mat(raw(:, 8));
binfieldbikey.VarName10 = cell2mat(raw(:, 9));
binfieldbikey.VarName11 = cell2mat(raw(:, 10));
binfieldbikey.VarName12 = cell2mat(raw(:, 11));
binfieldbikey.VarName13 = cell2mat(raw(:, 12));
binfieldbikey.VarName14 = cell2mat(raw(:, 13));
binfieldbikey.VarName15 = cell2mat(raw(:, 14));
binfieldbikey.VarName16 = cell2mat(raw(:, 15));
binfieldbikey.VarName17 = cell2mat(raw(:, 16));
binfieldbikey.VarName18 = cell2mat(raw(:, 17));
binfieldbikey.VarName19 = cell2mat(raw(:, 18));
binfieldbikey.VarName20 = cell2mat(raw(:, 19));
binfieldbikey.VarName21 = cell2mat(raw(:, 20));
binfieldbikey.VarName22 = cell2mat(raw(:, 21));
binfieldbikey.VarName23 = cell2mat(raw(:, 22));
binfieldbikey.VarName24 = cell2mat(raw(:, 23));
binfieldbikey.VarName25 = cell2mat(raw(:, 24));
binfieldbikey.VarName26 = cell2mat(raw(:, 25));
binfieldbikey.VarName27 = cell2mat(raw(:, 26));
binfieldbikey.VarName28 = cell2mat(raw(:, 27));
binfieldbikey.VarName29 = cell2mat(raw(:, 28));
binfieldbikey.VarName30 = cell2mat(raw(:, 29));
binfieldbikey.VarName31 = cell2mat(raw(:, 30));
binfieldbikey.VarName32 = cell2mat(raw(:, 31));
binfieldbikey.VarName33 = cell2mat(raw(:, 32));
binfieldbikey.VarName34 = cell2mat(raw(:, 33));
binfieldbikey.VarName35 = cell2mat(raw(:, 34));
binfieldbikey.VarName36 = cell2mat(raw(:, 35));
binfieldbikey.VarName37 = cell2mat(raw(:, 36));
binfieldbikey.VarName38 = cell2mat(raw(:, 37));
binfieldbikey.VarName39 = cell2mat(raw(:, 38));
binfieldbikey.VarName40 = cell2mat(raw(:, 39));
binfieldbikey.VarName41 = cell2mat(raw(:, 40));
binfieldbikey.VarName42 = cell2mat(raw(:, 41));
binfieldbikey.VarName43 = cell2mat(raw(:, 42));
binfieldbikey.VarName44 = cell2mat(raw(:, 43));
binfieldbikey.VarName45 = cell2mat(raw(:, 44));
binfieldbikey.VarName46 = cell2mat(raw(:, 45));
binfieldbikey.VarName47 = cell2mat(raw(:, 46));
binfieldbikey.VarName48 = cell2mat(raw(:, 47));
binfieldbikey.VarName49 = cell2mat(raw(:, 48));
binfieldbikey.VarName50 = cell2mat(raw(:, 49));
binfieldbikey.VarName51 = cell2mat(raw(:, 50));
binfieldbikey.VarName52 = cell2mat(raw(:, 51));
binfieldbikey.VarName53 = cell2mat(raw(:, 52));
binfieldbikey.VarName54 = cell2mat(raw(:, 53));
binfieldbikey.VarName55 = cell2mat(raw(:, 54));
binfieldbikey.VarName56 = cell2mat(raw(:, 55));
binfieldbikey.VarName57 = cell2mat(raw(:, 56));
binfieldbikey.VarName58 = cell2mat(raw(:, 57));
binfieldbikey.VarName59 = cell2mat(raw(:, 58));
binfieldbikey.VarName60 = cell2mat(raw(:, 59));
binfieldbikey.VarName61 = cell2mat(raw(:, 60));
binfieldbikey.VarName62 = cell2mat(raw(:, 61));
binfieldbikey.VarName63 = cell2mat(raw(:, 62));
binfieldbikey.VarName64 = cell2mat(raw(:, 63));
binfieldbikey.VarName65 = cell2mat(raw(:, 64));
binfieldbikey.VarName66 = cell2mat(raw(:, 65));
binfieldbikey.VarName67 = cell2mat(raw(:, 66));
binfieldbikey.VarName68 = cell2mat(raw(:, 67));
binfieldbikey.VarName69 = cell2mat(raw(:, 68));
binfieldbikey.VarName70 = cell2mat(raw(:, 69));
binfieldbikey.VarName71 = cell2mat(raw(:, 70));
binfieldbikey.VarName72 = cell2mat(raw(:, 71));
binfieldbikey.VarName73 = cell2mat(raw(:, 72));
binfieldbikey.VarName74 = cell2mat(raw(:, 73));
binfieldbikey.VarName75 = cell2mat(raw(:, 74));
binfieldbikey.VarName76 = cell2mat(raw(:, 75));
binfieldbikey.VarName77 = cell2mat(raw(:, 76));
binfieldbikey.VarName78 = cell2mat(raw(:, 77));
binfieldbikey.VarName79 = cell2mat(raw(:, 78));
binfieldbikey.VarName80 = cell2mat(raw(:, 79));
binfieldbikey.VarName81 = cell2mat(raw(:, 80));
binfieldbikey.VarName82 = cell2mat(raw(:, 81));
binfieldbikey.VarName83 = cell2mat(raw(:, 82));
binfieldbikey.VarName84 = cell2mat(raw(:, 83));
binfieldbikey.VarName85 = cell2mat(raw(:, 84));
binfieldbikey.VarName86 = cell2mat(raw(:, 85));
binfieldbikey.VarName87 = cell2mat(raw(:, 86));
binfieldbikey.VarName88 = cell2mat(raw(:, 87));
binfieldbikey.VarName89 = cell2mat(raw(:, 88));
binfieldbikey.VarName90 = cell2mat(raw(:, 89));
binfieldbikey.VarName91 = cell2mat(raw(:, 90));
binfieldbikey.VarName92 = cell2mat(raw(:, 91));
binfieldbikey.VarName93 = cell2mat(raw(:, 92));
binfieldbikey.VarName94 = cell2mat(raw(:, 93));
binfieldbikey.VarName95 = cell2mat(raw(:, 94));
binfieldbikey.VarName96 = cell2mat(raw(:, 95));
binfieldbikey.VarName97 = cell2mat(raw(:, 96));
binfieldbikey.VarName98 = cell2mat(raw(:, 97));
binfieldbikey.VarName99 = cell2mat(raw(:, 98));
binfieldbikey.VarName100 = cell2mat(raw(:, 99));
binfieldbikey.VarName101 = cell2mat(raw(:, 100));
binfieldbikey.VarName102 = cell2mat(raw(:, 101));
binfieldbikey.VarName103 = cell2mat(raw(:, 102));
binfieldbikey.VarName104 = cell2mat(raw(:, 103));
binfieldbikey.VarName105 = cell2mat(raw(:, 104));
binfieldbikey.VarName106 = cell2mat(raw(:, 105));
binfieldbikey.VarName107 = cell2mat(raw(:, 106));
binfieldbikey.VarName108 = cell2mat(raw(:, 107));
binfieldbikey.VarName109 = cell2mat(raw(:, 108));
binfieldbikey.VarName110 = cell2mat(raw(:, 109));
binfieldbikey.VarName111 = cell2mat(raw(:, 110));
binfieldbikey.VarName112 = cell2mat(raw(:, 111));
binfieldbikey.VarName113 = cell2mat(raw(:, 112));
binfieldbikey.VarName114 = cell2mat(raw(:, 113));
binfieldbikey.VarName115 = cell2mat(raw(:, 114));
binfieldbikey.VarName116 = cell2mat(raw(:, 115));
binfieldbikey.VarName117 = cell2mat(raw(:, 116));
binfieldbikey.VarName118 = cell2mat(raw(:, 117));
binfieldbikey.VarName119 = cell2mat(raw(:, 118));
binfieldbikey.VarName120 = cell2mat(raw(:, 119));
binfieldbikey.VarName121 = cell2mat(raw(:, 120));
binfieldbikey.VarName122 = cell2mat(raw(:, 121));
binfieldbikey.VarName123 = cell2mat(raw(:, 122));
binfieldbikey.VarName124 = cell2mat(raw(:, 123));
binfieldbikey.VarName125 = cell2mat(raw(:, 124));
binfieldbikey.VarName126 = cell2mat(raw(:, 125));
binfieldbikey.VarName127 = cell2mat(raw(:, 126));
binfieldbikey.VarName128 = cell2mat(raw(:, 127));
binfieldbikey.VarName129 = cell2mat(raw(:, 128));
binfieldbikey.VarName130 = cell2mat(raw(:, 129));
binfieldbikey.VarName131 = cell2mat(raw(:, 130));
binfieldbikey.VarName132 = cell2mat(raw(:, 131));
binfieldbikey.VarName133 = cell2mat(raw(:, 132));
binfieldbikey.VarName134 = cell2mat(raw(:, 133));
binfieldbikey.VarName135 = cell2mat(raw(:, 134));
binfieldbikey.VarName136 = cell2mat(raw(:, 135));
binfieldbikey.VarName137 = cell2mat(raw(:, 136));
binfieldbikey.VarName138 = cell2mat(raw(:, 137));
binfieldbikey.VarName139 = cell2mat(raw(:, 138));
binfieldbikey.VarName140 = cell2mat(raw(:, 139));
binfieldbikey.VarName141 = cell2mat(raw(:, 140));
binfieldbikey.VarName142 = cell2mat(raw(:, 141));
binfieldbikey.VarName143 = cell2mat(raw(:, 142));
binfieldbikey.VarName144 = cell2mat(raw(:, 143));
binfieldbikey.VarName145 = cell2mat(raw(:, 144));
binfieldbikey.VarName146 = cell2mat(raw(:, 145));
binfieldbikey.VarName147 = cell2mat(raw(:, 146));
binfieldbikey.VarName148 = cell2mat(raw(:, 147));
binfieldbikey.VarName149 = cell2mat(raw(:, 148));
binfieldbikey.VarName150 = cell2mat(raw(:, 149));
binfieldbikey.VarName151 = cell2mat(raw(:, 150));
binfieldbikey.VarName152 = cell2mat(raw(:, 151));
binfieldbikey.VarName153 = cell2mat(raw(:, 152));
binfieldbikey.VarName154 = cell2mat(raw(:, 153));
binfieldbikey.VarName155 = cell2mat(raw(:, 154));
binfieldbikey.VarName156 = cell2mat(raw(:, 155));
binfieldbikey.VarName157 = cell2mat(raw(:, 156));
binfieldbikey.VarName158 = cell2mat(raw(:, 157));
binfieldbikey.VarName159 = cell2mat(raw(:, 158));
binfieldbikey.VarName160 = cell2mat(raw(:, 159));
binfieldbikey.VarName161 = cell2mat(raw(:, 160));
binfieldbikey.VarName162 = cell2mat(raw(:, 161));
binfieldbikey.VarName163 = cell2mat(raw(:, 162));
binfieldbikey.VarName164 = cell2mat(raw(:, 163));
binfieldbikey.VarName165 = cell2mat(raw(:, 164));
binfieldbikey.VarName166 = cell2mat(raw(:, 165));
binfieldbikey.VarName167 = cell2mat(raw(:, 166));
binfieldbikey.VarName168 = cell2mat(raw(:, 167));
binfieldbikey.VarName169 = cell2mat(raw(:, 168));
binfieldbikey.VarName170 = cell2mat(raw(:, 169));
binfieldbikey.VarName171 = cell2mat(raw(:, 170));
binfieldbikey.VarName172 = cell2mat(raw(:, 171));
binfieldbikey.VarName173 = cell2mat(raw(:, 172));
binfieldbikey.VarName174 = cell2mat(raw(:, 173));
binfieldbikey.VarName175 = cell2mat(raw(:, 174));
binfieldbikey.VarName176 = cell2mat(raw(:, 175));
binfieldbikey.VarName177 = cell2mat(raw(:, 176));
binfieldbikey.VarName178 = cell2mat(raw(:, 177));
binfieldbikey.VarName179 = cell2mat(raw(:, 178));
binfieldbikey.VarName180 = cell2mat(raw(:, 179));
binfieldbikey.VarName181 = cell2mat(raw(:, 180));
binfieldbikey.VarName182 = cell2mat(raw(:, 181));
binfieldbikey.VarName183 = cell2mat(raw(:, 182));
binfieldbikey.VarName184 = cell2mat(raw(:, 183));
binfieldbikey.VarName185 = cell2mat(raw(:, 184));
binfieldbikey.VarName186 = cell2mat(raw(:, 185));
binfieldbikey.VarName187 = cell2mat(raw(:, 186));
binfieldbikey.VarName188 = cell2mat(raw(:, 187));
binfieldbikey.VarName189 = cell2mat(raw(:, 188));
binfieldbikey.VarName190 = cell2mat(raw(:, 189));
binfieldbikey.VarName191 = cell2mat(raw(:, 190));
binfieldbikey.VarName192 = cell2mat(raw(:, 191));
binfieldbikey.VarName193 = cell2mat(raw(:, 192));
binfieldbikey.VarName194 = cell2mat(raw(:, 193));
binfieldbikey.VarName195 = cell2mat(raw(:, 194));
binfieldbikey.VarName196 = cell2mat(raw(:, 195));
binfieldbikey.VarName197 = cell2mat(raw(:, 196));
binfieldbikey.VarName198 = cell2mat(raw(:, 197));
binfieldbikey.VarName199 = cell2mat(raw(:, 198));
binfieldbikey.VarName200 = cell2mat(raw(:, 199));
binfieldbikey.VarName201 = cell2mat(raw(:, 200));
binfieldbikey.VarName202 = cell2mat(raw(:, 201));
binfieldbikey.VarName203 = cell2mat(raw(:, 202));
binfieldbikey.VarName204 = cell2mat(raw(:, 203));
binfieldbikey.VarName205 = cell2mat(raw(:, 204));
binfieldbikey.VarName206 = cell2mat(raw(:, 205));
binfieldbikey.VarName207 = cell2mat(raw(:, 206));
binfieldbikey.VarName208 = cell2mat(raw(:, 207));
binfieldbikey.VarName209 = cell2mat(raw(:, 208));
binfieldbikey.VarName210 = cell2mat(raw(:, 209));
binfieldbikey.VarName211 = cell2mat(raw(:, 210));
binfieldbikey.VarName212 = cell2mat(raw(:, 211));
binfieldbikey.VarName213 = cell2mat(raw(:, 212));
binfieldbikey.VarName214 = cell2mat(raw(:, 213));
binfieldbikey.VarName215 = cell2mat(raw(:, 214));
binfieldbikey.VarName216 = cell2mat(raw(:, 215));
binfieldbikey.VarName217 = cell2mat(raw(:, 216));
binfieldbikey.VarName218 = cell2mat(raw(:, 217));
binfieldbikey.VarName219 = cell2mat(raw(:, 218));
binfieldbikey.VarName220 = cell2mat(raw(:, 219));
binfieldbikey.VarName221 = cell2mat(raw(:, 220));
binfieldbikey.VarName222 = cell2mat(raw(:, 221));
binfieldbikey.VarName223 = cell2mat(raw(:, 222));
binfieldbikey.VarName224 = cell2mat(raw(:, 223));
binfieldbikey.VarName225 = cell2mat(raw(:, 224));
binfieldbikey.VarName226 = cell2mat(raw(:, 225));
binfieldbikey.VarName227 = cell2mat(raw(:, 226));
binfieldbikey.VarName228 = cell2mat(raw(:, 227));
binfieldbikey.VarName229 = cell2mat(raw(:, 228));
binfieldbikey.VarName230 = cell2mat(raw(:, 229));
binfieldbikey.VarName231 = cell2mat(raw(:, 230));
binfieldbikey.VarName232 = cell2mat(raw(:, 231));
binfieldbikey.VarName233 = cell2mat(raw(:, 232));
binfieldbikey.VarName234 = cell2mat(raw(:, 233));
binfieldbikey.VarName235 = cell2mat(raw(:, 234));
binfieldbikey.VarName236 = cell2mat(raw(:, 235));
binfieldbikey.VarName237 = cell2mat(raw(:, 236));
binfieldbikey.VarName238 = cell2mat(raw(:, 237));
binfieldbikey.VarName239 = cell2mat(raw(:, 238));
binfieldbikey.VarName240 = cell2mat(raw(:, 239));
binfieldbikey.VarName241 = cell2mat(raw(:, 240));

