function binfieldbike1 = importfile_bin_bike(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   BINFIELDBIKE1 = IMPORTFILE(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   BINFIELDBIKE1 = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   binfieldbike1 = importfile('binfield_bike.txt', 2, 504);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2024/01/02 11:50:46

%% Initialize variables.
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*3s%24s%14s%14s%13s%13s%13s%13s%14s%14s%13s%13s%14s%13s%14s%14s%13s%13s%13s%13s%14s%14s%13s%13s%14s%13s%14s%14s%13s%13s%13s%13s%14s%14s%13s%14s%14s%13s%14s%14s%13s%13s%13s%13s%14s%14s%13s%14s%14s%13s%14s%14s%13s%13s%13s%13s%14s%14s%13s%14s%14s%13s%14s%14s%13s%13s%13s%13s%14s%14s%13s%14s%14s%13s%14s%14s%13s%13s%13s%13s%14s%14s%13s%14s%14s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%14s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%14s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%14s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%14s%13s%14s%14s%13s%13s%13s%13s%14s%14s%13s%14s%14s%13s%14s%14s%13s%13s%13s%13s%14s%14s%13s%14s%14s%13s%14s%14s%13s%13s%13s%13s%14s%14s%13s%14s%14s%13s%14s%14s%13s%13s%13s%13s%14s%14s%13s%14s%14s%13s%14s%14s%13s%13s%13s%13s%14s%14s%13s%14s%14s%13s%14s%14s%13s%13s%13s%13s%14s%14s%13s%14s%14s%13s%14s%14s%13s%13s%13s%13s%14s%14s%13s%14s%14s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%14s%13s%14s%13s%13s%13s%13s%13s%14s%13s%13s%14s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'WhiteSpace', '', 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240]
    % Converts text in the input cell array to numbers. Replaced non-numeric text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;

            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^[-/+]*\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
binfieldbike1 = table;
binfieldbike1.FieldBike15cmBlockMe = cell2mat(raw(:, 1));
binfieldbike1.shLast500I = cell2mat(raw(:, 2));
binfieldbike1.terations300 = cell2mat(raw(:, 3));
binfieldbike1.VarName5 = cell2mat(raw(:, 4));
binfieldbike1.VarName6 = cell2mat(raw(:, 5));
binfieldbike1.VarName7 = cell2mat(raw(:, 6));
binfieldbike1.VarName8 = cell2mat(raw(:, 7));
binfieldbike1.VarName9 = cell2mat(raw(:, 8));
binfieldbike1.VarName10 = cell2mat(raw(:, 9));
binfieldbike1.VarName11 = cell2mat(raw(:, 10));
binfieldbike1.VarName12 = cell2mat(raw(:, 11));
binfieldbike1.VarName13 = cell2mat(raw(:, 12));
binfieldbike1.VarName14 = cell2mat(raw(:, 13));
binfieldbike1.VarName15 = cell2mat(raw(:, 14));
binfieldbike1.VarName16 = cell2mat(raw(:, 15));
binfieldbike1.VarName17 = cell2mat(raw(:, 16));
binfieldbike1.VarName18 = cell2mat(raw(:, 17));
binfieldbike1.VarName19 = cell2mat(raw(:, 18));
binfieldbike1.VarName20 = cell2mat(raw(:, 19));
binfieldbike1.VarName21 = cell2mat(raw(:, 20));
binfieldbike1.VarName22 = cell2mat(raw(:, 21));
binfieldbike1.VarName23 = cell2mat(raw(:, 22));
binfieldbike1.VarName24 = cell2mat(raw(:, 23));
binfieldbike1.VarName25 = cell2mat(raw(:, 24));
binfieldbike1.VarName26 = cell2mat(raw(:, 25));
binfieldbike1.VarName27 = cell2mat(raw(:, 26));
binfieldbike1.VarName28 = cell2mat(raw(:, 27));
binfieldbike1.VarName29 = cell2mat(raw(:, 28));
binfieldbike1.VarName30 = cell2mat(raw(:, 29));
binfieldbike1.VarName31 = cell2mat(raw(:, 30));
binfieldbike1.VarName32 = cell2mat(raw(:, 31));
binfieldbike1.VarName33 = cell2mat(raw(:, 32));
binfieldbike1.VarName34 = cell2mat(raw(:, 33));
binfieldbike1.VarName35 = cell2mat(raw(:, 34));
binfieldbike1.VarName36 = cell2mat(raw(:, 35));
binfieldbike1.VarName37 = cell2mat(raw(:, 36));
binfieldbike1.VarName38 = cell2mat(raw(:, 37));
binfieldbike1.VarName39 = cell2mat(raw(:, 38));
binfieldbike1.VarName40 = cell2mat(raw(:, 39));
binfieldbike1.VarName41 = cell2mat(raw(:, 40));
binfieldbike1.VarName42 = cell2mat(raw(:, 41));
binfieldbike1.VarName43 = cell2mat(raw(:, 42));
binfieldbike1.VarName44 = cell2mat(raw(:, 43));
binfieldbike1.VarName45 = cell2mat(raw(:, 44));
binfieldbike1.VarName46 = cell2mat(raw(:, 45));
binfieldbike1.VarName47 = cell2mat(raw(:, 46));
binfieldbike1.VarName48 = cell2mat(raw(:, 47));
binfieldbike1.VarName49 = cell2mat(raw(:, 48));
binfieldbike1.VarName50 = cell2mat(raw(:, 49));
binfieldbike1.VarName51 = cell2mat(raw(:, 50));
binfieldbike1.VarName52 = cell2mat(raw(:, 51));
binfieldbike1.VarName53 = cell2mat(raw(:, 52));
binfieldbike1.VarName54 = cell2mat(raw(:, 53));
binfieldbike1.VarName55 = cell2mat(raw(:, 54));
binfieldbike1.VarName56 = cell2mat(raw(:, 55));
binfieldbike1.VarName57 = cell2mat(raw(:, 56));
binfieldbike1.VarName58 = cell2mat(raw(:, 57));
binfieldbike1.VarName59 = cell2mat(raw(:, 58));
binfieldbike1.VarName60 = cell2mat(raw(:, 59));
binfieldbike1.VarName61 = cell2mat(raw(:, 60));
binfieldbike1.VarName62 = cell2mat(raw(:, 61));
binfieldbike1.VarName63 = cell2mat(raw(:, 62));
binfieldbike1.VarName64 = cell2mat(raw(:, 63));
binfieldbike1.VarName65 = cell2mat(raw(:, 64));
binfieldbike1.VarName66 = cell2mat(raw(:, 65));
binfieldbike1.VarName67 = cell2mat(raw(:, 66));
binfieldbike1.VarName68 = cell2mat(raw(:, 67));
binfieldbike1.VarName69 = cell2mat(raw(:, 68));
binfieldbike1.VarName70 = cell2mat(raw(:, 69));
binfieldbike1.VarName71 = cell2mat(raw(:, 70));
binfieldbike1.VarName72 = cell2mat(raw(:, 71));
binfieldbike1.VarName73 = cell2mat(raw(:, 72));
binfieldbike1.VarName74 = cell2mat(raw(:, 73));
binfieldbike1.VarName75 = cell2mat(raw(:, 74));
binfieldbike1.VarName76 = cell2mat(raw(:, 75));
binfieldbike1.VarName77 = cell2mat(raw(:, 76));
binfieldbike1.VarName78 = cell2mat(raw(:, 77));
binfieldbike1.VarName79 = cell2mat(raw(:, 78));
binfieldbike1.VarName80 = cell2mat(raw(:, 79));
binfieldbike1.VarName81 = cell2mat(raw(:, 80));
binfieldbike1.VarName82 = cell2mat(raw(:, 81));
binfieldbike1.VarName83 = cell2mat(raw(:, 82));
binfieldbike1.VarName84 = cell2mat(raw(:, 83));
binfieldbike1.VarName85 = cell2mat(raw(:, 84));
binfieldbike1.VarName86 = cell2mat(raw(:, 85));
binfieldbike1.VarName87 = cell2mat(raw(:, 86));
binfieldbike1.VarName88 = cell2mat(raw(:, 87));
binfieldbike1.VarName89 = cell2mat(raw(:, 88));
binfieldbike1.VarName90 = cell2mat(raw(:, 89));
binfieldbike1.VarName91 = cell2mat(raw(:, 90));
binfieldbike1.VarName92 = cell2mat(raw(:, 91));
binfieldbike1.VarName93 = cell2mat(raw(:, 92));
binfieldbike1.VarName94 = cell2mat(raw(:, 93));
binfieldbike1.VarName95 = cell2mat(raw(:, 94));
binfieldbike1.VarName96 = cell2mat(raw(:, 95));
binfieldbike1.VarName97 = cell2mat(raw(:, 96));
binfieldbike1.VarName98 = cell2mat(raw(:, 97));
binfieldbike1.VarName99 = cell2mat(raw(:, 98));
binfieldbike1.VarName100 = cell2mat(raw(:, 99));
binfieldbike1.VarName101 = cell2mat(raw(:, 100));
binfieldbike1.VarName102 = cell2mat(raw(:, 101));
binfieldbike1.VarName103 = cell2mat(raw(:, 102));
binfieldbike1.VarName104 = cell2mat(raw(:, 103));
binfieldbike1.VarName105 = cell2mat(raw(:, 104));
binfieldbike1.VarName106 = cell2mat(raw(:, 105));
binfieldbike1.VarName107 = cell2mat(raw(:, 106));
binfieldbike1.VarName108 = cell2mat(raw(:, 107));
binfieldbike1.VarName109 = cell2mat(raw(:, 108));
binfieldbike1.VarName110 = cell2mat(raw(:, 109));
binfieldbike1.VarName111 = cell2mat(raw(:, 110));
binfieldbike1.VarName112 = cell2mat(raw(:, 111));
binfieldbike1.VarName113 = cell2mat(raw(:, 112));
binfieldbike1.VarName114 = cell2mat(raw(:, 113));
binfieldbike1.VarName115 = cell2mat(raw(:, 114));
binfieldbike1.VarName116 = cell2mat(raw(:, 115));
binfieldbike1.VarName117 = cell2mat(raw(:, 116));
binfieldbike1.VarName118 = cell2mat(raw(:, 117));
binfieldbike1.VarName119 = cell2mat(raw(:, 118));
binfieldbike1.VarName120 = cell2mat(raw(:, 119));
binfieldbike1.VarName121 = cell2mat(raw(:, 120));
binfieldbike1.VarName122 = cell2mat(raw(:, 121));
binfieldbike1.VarName123 = cell2mat(raw(:, 122));
binfieldbike1.VarName124 = cell2mat(raw(:, 123));
binfieldbike1.VarName125 = cell2mat(raw(:, 124));
binfieldbike1.VarName126 = cell2mat(raw(:, 125));
binfieldbike1.VarName127 = cell2mat(raw(:, 126));
binfieldbike1.VarName128 = cell2mat(raw(:, 127));
binfieldbike1.VarName129 = cell2mat(raw(:, 128));
binfieldbike1.VarName130 = cell2mat(raw(:, 129));
binfieldbike1.VarName131 = cell2mat(raw(:, 130));
binfieldbike1.VarName132 = cell2mat(raw(:, 131));
binfieldbike1.VarName133 = cell2mat(raw(:, 132));
binfieldbike1.VarName134 = cell2mat(raw(:, 133));
binfieldbike1.VarName135 = cell2mat(raw(:, 134));
binfieldbike1.VarName136 = cell2mat(raw(:, 135));
binfieldbike1.VarName137 = cell2mat(raw(:, 136));
binfieldbike1.VarName138 = cell2mat(raw(:, 137));
binfieldbike1.VarName139 = cell2mat(raw(:, 138));
binfieldbike1.VarName140 = cell2mat(raw(:, 139));
binfieldbike1.VarName141 = cell2mat(raw(:, 140));
binfieldbike1.VarName142 = cell2mat(raw(:, 141));
binfieldbike1.VarName143 = cell2mat(raw(:, 142));
binfieldbike1.VarName144 = cell2mat(raw(:, 143));
binfieldbike1.VarName145 = cell2mat(raw(:, 144));
binfieldbike1.VarName146 = cell2mat(raw(:, 145));
binfieldbike1.VarName147 = cell2mat(raw(:, 146));
binfieldbike1.VarName148 = cell2mat(raw(:, 147));
binfieldbike1.VarName149 = cell2mat(raw(:, 148));
binfieldbike1.VarName150 = cell2mat(raw(:, 149));
binfieldbike1.VarName151 = cell2mat(raw(:, 150));
binfieldbike1.VarName152 = cell2mat(raw(:, 151));
binfieldbike1.VarName153 = cell2mat(raw(:, 152));
binfieldbike1.VarName154 = cell2mat(raw(:, 153));
binfieldbike1.VarName155 = cell2mat(raw(:, 154));
binfieldbike1.VarName156 = cell2mat(raw(:, 155));
binfieldbike1.VarName157 = cell2mat(raw(:, 156));
binfieldbike1.VarName158 = cell2mat(raw(:, 157));
binfieldbike1.VarName159 = cell2mat(raw(:, 158));
binfieldbike1.VarName160 = cell2mat(raw(:, 159));
binfieldbike1.VarName161 = cell2mat(raw(:, 160));
binfieldbike1.VarName162 = cell2mat(raw(:, 161));
binfieldbike1.VarName163 = cell2mat(raw(:, 162));
binfieldbike1.VarName164 = cell2mat(raw(:, 163));
binfieldbike1.VarName165 = cell2mat(raw(:, 164));
binfieldbike1.VarName166 = cell2mat(raw(:, 165));
binfieldbike1.VarName167 = cell2mat(raw(:, 166));
binfieldbike1.VarName168 = cell2mat(raw(:, 167));
binfieldbike1.VarName169 = cell2mat(raw(:, 168));
binfieldbike1.VarName170 = cell2mat(raw(:, 169));
binfieldbike1.VarName171 = cell2mat(raw(:, 170));
binfieldbike1.VarName172 = cell2mat(raw(:, 171));
binfieldbike1.VarName173 = cell2mat(raw(:, 172));
binfieldbike1.VarName174 = cell2mat(raw(:, 173));
binfieldbike1.VarName175 = cell2mat(raw(:, 174));
binfieldbike1.VarName176 = cell2mat(raw(:, 175));
binfieldbike1.VarName177 = cell2mat(raw(:, 176));
binfieldbike1.VarName178 = cell2mat(raw(:, 177));
binfieldbike1.VarName179 = cell2mat(raw(:, 178));
binfieldbike1.VarName180 = cell2mat(raw(:, 179));
binfieldbike1.VarName181 = cell2mat(raw(:, 180));
binfieldbike1.VarName182 = cell2mat(raw(:, 181));
binfieldbike1.VarName183 = cell2mat(raw(:, 182));
binfieldbike1.VarName184 = cell2mat(raw(:, 183));
binfieldbike1.VarName185 = cell2mat(raw(:, 184));
binfieldbike1.VarName186 = cell2mat(raw(:, 185));
binfieldbike1.VarName187 = cell2mat(raw(:, 186));
binfieldbike1.VarName188 = cell2mat(raw(:, 187));
binfieldbike1.VarName189 = cell2mat(raw(:, 188));
binfieldbike1.VarName190 = cell2mat(raw(:, 189));
binfieldbike1.VarName191 = cell2mat(raw(:, 190));
binfieldbike1.VarName192 = cell2mat(raw(:, 191));
binfieldbike1.VarName193 = cell2mat(raw(:, 192));
binfieldbike1.VarName194 = cell2mat(raw(:, 193));
binfieldbike1.VarName195 = cell2mat(raw(:, 194));
binfieldbike1.VarName196 = cell2mat(raw(:, 195));
binfieldbike1.VarName197 = cell2mat(raw(:, 196));
binfieldbike1.VarName198 = cell2mat(raw(:, 197));
binfieldbike1.VarName199 = cell2mat(raw(:, 198));
binfieldbike1.VarName200 = cell2mat(raw(:, 199));
binfieldbike1.VarName201 = cell2mat(raw(:, 200));
binfieldbike1.VarName202 = cell2mat(raw(:, 201));
binfieldbike1.VarName203 = cell2mat(raw(:, 202));
binfieldbike1.VarName204 = cell2mat(raw(:, 203));
binfieldbike1.VarName205 = cell2mat(raw(:, 204));
binfieldbike1.VarName206 = cell2mat(raw(:, 205));
binfieldbike1.VarName207 = cell2mat(raw(:, 206));
binfieldbike1.VarName208 = cell2mat(raw(:, 207));
binfieldbike1.VarName209 = cell2mat(raw(:, 208));
binfieldbike1.VarName210 = cell2mat(raw(:, 209));
binfieldbike1.VarName211 = cell2mat(raw(:, 210));
binfieldbike1.VarName212 = cell2mat(raw(:, 211));
binfieldbike1.VarName213 = cell2mat(raw(:, 212));
binfieldbike1.VarName214 = cell2mat(raw(:, 213));
binfieldbike1.VarName215 = cell2mat(raw(:, 214));
binfieldbike1.VarName216 = cell2mat(raw(:, 215));
binfieldbike1.VarName217 = cell2mat(raw(:, 216));
binfieldbike1.VarName218 = cell2mat(raw(:, 217));
binfieldbike1.VarName219 = cell2mat(raw(:, 218));
binfieldbike1.VarName220 = cell2mat(raw(:, 219));
binfieldbike1.VarName221 = cell2mat(raw(:, 220));
binfieldbike1.VarName222 = cell2mat(raw(:, 221));
binfieldbike1.VarName223 = cell2mat(raw(:, 222));
binfieldbike1.VarName224 = cell2mat(raw(:, 223));
binfieldbike1.VarName225 = cell2mat(raw(:, 224));
binfieldbike1.VarName226 = cell2mat(raw(:, 225));
binfieldbike1.VarName227 = cell2mat(raw(:, 226));
binfieldbike1.VarName228 = cell2mat(raw(:, 227));
binfieldbike1.VarName229 = cell2mat(raw(:, 228));
binfieldbike1.VarName230 = cell2mat(raw(:, 229));
binfieldbike1.VarName231 = cell2mat(raw(:, 230));
binfieldbike1.VarName232 = cell2mat(raw(:, 231));
binfieldbike1.VarName233 = cell2mat(raw(:, 232));
binfieldbike1.VarName234 = cell2mat(raw(:, 233));
binfieldbike1.VarName235 = cell2mat(raw(:, 234));
binfieldbike1.VarName236 = cell2mat(raw(:, 235));
binfieldbike1.VarName237 = cell2mat(raw(:, 236));
binfieldbike1.VarName238 = cell2mat(raw(:, 237));
binfieldbike1.VarName239 = cell2mat(raw(:, 238));
binfieldbike1.VarName240 = cell2mat(raw(:, 239));
binfieldbike1.VarName241 = cell2mat(raw(:, 240));

